import os

BACKLOG_SPACE = os.environ['BACKLOG_SPACE']
BACKLOG_API_KEY = os.environ['BACKLOG_API_KEY']
BACKLOG_DEFAULT_PROJECT_ID = os.environ['BACKLOG_DEFAULT_PROJECT_ID']
BACKLOG_DEFAULT_PROJECT_KEY = os.environ['BACKLOG_DEFAULT_PROJECT_KEY']
BACKLOG_DEFAULT_ISSUE_TYPE = os.environ['BACKLOG_DEFAULT_ISSUE_TYPE']
BACKLOG_DEFAULT_PRIORITY = os.environ['BACKLOG_DEFAULT_PRIORITY']
BACKLOG_DEFAULT_ISSUE_CREATE_STATUS = os.environ['BACKLOG_DEFAULT_ISSUE_CREATE_STATUS']
BACKLOG_DEFAULT_ISSUE_INPROGRESS_STATUS = os.environ['BACKLOG_DEFAULT_ISSUE_INPROGRESS_STATUS']
BACKLOG_DEFAULT_ISSUE_RESOLVE_STATUS = os.environ['BACKLOG_DEFAULT_ISSUE_RESOLVE_STATUS']

DDB_TABLE = 'table'